#ifndef WHEY_H
#define WHEY_H

#define WHEY_VERSION_MAJOR "0"
#define WHEY_VERSION_MINOR "1"

#define WHEY_VERSION "Whey " WHEY_VERSION_MAJOR "." WHEY_VERSION_MINOR

#define WHEY_SIZE_OPERAND_STACK         25

#endif